server:
  port: $PORT

spring:
  data:
    mongodb:
      uri: mongodb+srv://root:zx6666662@garycoffeelog.aknu3.mongodb.net/garyCoffeeLog
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8